# Generated by Django 5.2.4 on 2025-08-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_products'),
    ]

    operations = [migrations.RunSQL("""
        INSERT INTO store_collection (title)
        VALUES ('collection1')
        """,
        """
        DELETE FROM store_collection
        WHERE title = 'collection1'
        """)
    ]
