# Generated by Django 5.2.4 on 2025-08-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
