# Generated by Django 5.2.4 on 2025-08-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_prize',
            new_name='unit_price',
        ),
    ]
