# Generated by Django 5.2.4 on 2025-08-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can canel order')]},
        ),
    ]
